'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import { Provider } from "react-redux";
import { store } from "@/Libraries/store";
import { Toaster } from "react-hot-toast";
import ProtectedRoute from "./_Components/ProtectedRoute/ProtectedRoute";
import PostsContext from "@/Context/PostsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Provider store={store}>
        <Navbar/> 
      <ProtectedRoute>
          <Toaster/>
       <div className='mt-14 pt-10'>
    
      <PostsContext>
      {children}
      </PostsContext>
       </div>

      </ProtectedRoute>
        </Provider>
      </body>
    </html>
  );
}
